't" t
.TH MathematicaMCMC 1 "January 2019" UNIX "NagBody PROJECT"
.na
.nh   

.SH NAME
MathematicaMCMC - Mathematica notebook to analyse data using bayesian MCMC method.
.SH SYNOPSIS
\fBMathematicaMCMC\fR
.sp

.SH DESCRIPTION
\fBMathematicaMCMC\fR - MCMC to analyse data versus models using bayesian MCMC method.

.SH OPTIONS
Open the notebook...
.sp

.SH EXAMPLES
Open MathematicaMCMC notebook and run it. Where notebook is copy a file with RC data for a galaxy, for example the IC 2574 galaxy included with the distribution.

.sp
When finish running you will have a folder "Results" with the results. You may analyse the chains using GetDist code.

.SH SEE ALSO
nmcmc(1) and GetDist

.SH COPYRIGHT
Copyright (C) 1999-2019
.br
Mario A. Rodriguez-Meza
.br
